### session 2: NumPy applications
1. Create a 2*3 array in numpy, name it a.
2. Creat a 2 * 3 * 3 array and write the code for accessing the 2nd element of the 3rd. 
3. Reshape a 2 * 10 array to 5 * 4.
4. Create a 8*8 matrix that all of its elements are 7 and convert it to an array with just one column.
5. Create two 4*4 arrays and calculate the four basic arithmatic operations.
6. Concatenate two arrays of section 4. 

In [4]:
import numpy as np
from numpy import random

a = np.array([[1, 2], [3, 4], [5, 6]])

a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
b = np.array(([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))

b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
b[0,2,1] #we do not have 2nd element of 3rd dimention (the size of third dimention is 2)

8

In [9]:
c = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]])

c1 = c.reshape(5, 4)

c1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [10]:
d = np.full([8, 8], 7)

d

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [11]:
d1 = d.reshape(-1)

d1

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [12]:
d2 = d.flatten()

d2

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [13]:
d3 = d.reshape((-1,1))

d3

"""
https://stackoverflow.com/questions/5954603/transposing-a-1d-numpy-array

"""

'\nhttps://stackoverflow.com/questions/5954603/transposing-a-1d-numpy-array\n\n'

In [14]:
e1 = random.randint(50, size=(4, 4))
e2 = random.randint(20, size=(4, 4))

e1

array([[11,  6, 27, 46],
       [ 5, 32, 28, 32],
       [ 5, 32, 11, 40],
       [28, 28, 27, 37]])

In [15]:
e2

array([[ 0,  4, 10,  2],
       [16, 16,  9,  8],
       [14, 12, 18, 13],
       [ 3, 14,  0, 13]])

In [16]:
np.add(e1, e2)

array([[11, 10, 37, 48],
       [21, 48, 37, 40],
       [19, 44, 29, 53],
       [31, 42, 27, 50]])

In [18]:
np.subtract(e1, e2)

array([[ 11,   2,  17,  44],
       [-11,  16,  19,  24],
       [ -9,  20,  -7,  27],
       [ 25,  14,  27,  24]])

In [19]:
np.multiply(e1, e2)

array([[  0,  24, 270,  92],
       [ 80, 512, 252, 256],
       [ 70, 384, 198, 520],
       [ 84, 392,   0, 481]])

In [20]:
np.divide(e1, e2)

<ipython-input-20-4425262fdca3>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(e1, e2)


array([[        inf,  1.5       ,  2.7       , 23.        ],
       [ 0.3125    ,  2.        ,  3.11111111,  4.        ],
       [ 0.35714286,  2.66666667,  0.61111111,  3.07692308],
       [ 9.33333333,  2.        ,         inf,  2.84615385]])

In [22]:
e3 = np.concatenate((e1, e2))

e3

array([[11,  6, 27, 46],
       [ 5, 32, 28, 32],
       [ 5, 32, 11, 40],
       [28, 28, 27, 37],
       [ 0,  4, 10,  2],
       [16, 16,  9,  8],
       [14, 12, 18, 13],
       [ 3, 14,  0, 13]])

In [24]:
e4 = np.stack((e1, e2),axis=1)

e4

array([[[11,  6, 27, 46],
        [ 0,  4, 10,  2]],

       [[ 5, 32, 28, 32],
        [16, 16,  9,  8]],

       [[ 5, 32, 11, 40],
        [14, 12, 18, 13]],

       [[28, 28, 27, 37],
        [ 3, 14,  0, 13]]])