### session 2: NumPy applications
1. Create a 2*3 array in numpy, name it a.
2. Creat a 2*3*3 array and write the code for accessing the 2nd element of the 3rd. 
3. Reshape a 2 * 10 array to 5 * 4.
4. Create a 8*8 matrix that all of its elements are 7 and convert it to an array with just one column.
5. Create two 4*4 arrays and calculate the four basic arithmatic operations.
6. Concatenate two arrays of section 4. 

In [24]:
import numpy as np
from numpy import random

a = np.array([[1, 2], [3, 4], [5, 6]])

a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
b = np.array(([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))

b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
b[2,1] #we do not have 2nd element of 3rd dimention (the size of third dimention is 2)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [27]:
c = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]])

c1 = c.reshape(5, 4)

c1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [28]:
d = np.full([8, 8], 7)

d

array([[7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [29]:
d1 = d.reshape(-1)

d1

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [30]:
d2 = d.flatten()

d2

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [31]:
d3 = d.reshape((-1,1))

d3

"""
https://stackoverflow.com/questions/5954603/transposing-a-1d-numpy-array

"""

'\nhttps://stackoverflow.com/questions/5954603/transposing-a-1d-numpy-array\n\n'

In [32]:
e1 = random.randint(50, size=(4, 4))
e2 = random.randint(20, size=(4, 4))

e1

array([[ 5, 49, 49, 46],
       [19, 36,  8,  0],
       [ 3, 34, 48, 24],
       [25,  9,  1, 33]])

In [33]:
e2

array([[17,  0, 12, 16],
       [ 2, 18, 12,  9],
       [ 5,  5, 15,  9],
       [19, 18,  5,  4]])

In [34]:
e1 + e2

array([[22, 49, 61, 62],
       [21, 54, 20,  9],
       [ 8, 39, 63, 33],
       [44, 27,  6, 37]])

In [35]:
e1 - e2

array([[-12,  49,  37,  30],
       [ 17,  18,  -4,  -9],
       [ -2,  29,  33,  15],
       [  6,  -9,  -4,  29]])

In [36]:
e1 * e2

array([[ 85,   0, 588, 736],
       [ 38, 648,  96,   0],
       [ 15, 170, 720, 216],
       [475, 162,   5, 132]])

In [39]:
e1 / e2

<ipython-input-39-d76a943d8321>:1: RuntimeWarning: divide by zero encountered in true_divide
  e1 / e2


array([[0.29411765,        inf, 4.08333333, 2.875     ],
       [9.5       , 2.        , 0.66666667, 0.        ],
       [0.6       , 6.8       , 3.2       , 2.66666667],
       [1.31578947, 0.5       , 0.2       , 8.25      ]])

In [42]:
e3 = np.concatenate((e1, e2))

e3

array([[ 5, 49, 49, 46],
       [19, 36,  8,  0],
       [ 3, 34, 48, 24],
       [25,  9,  1, 33],
       [17,  0, 12, 16],
       [ 2, 18, 12,  9],
       [ 5,  5, 15,  9],
       [19, 18,  5,  4]])